
### Homework #2 - Functions,Loops, Conditionals

1.  Do 5 CodeWars problems in R. Share your solutions here:

 make_negative <- function(number) {
  if (number > 0) {
    return(-number)
  } else {
    return(number)
  }
}


invert <- function(vec) {
  inverted_numbers <- -vec
  return(inverted_numbers)
}


a <- "code"
b <- "wa.rs"
name <-  paste(a,b, sep='')


greet <- function() {
     return(as.character("hello world!"))}
result <- greet
     
     
number_to_string <- function(num) {
  return(as.character(num))
}



2.  Create a function that checks an input of type `int` and returns fizz if the number is a multiple of 3, buzz if the number is a multiple of 5, and fizzbuzz if the number is a multiple of 3 and 5.

check_integer <- function(s) {
  if (as.integer(s) %% 3 == 0 && as.integer(s) %% 5 == 0) {
    print("fizzbuzz")
  } else if (as.integer(s) %% 3 == 0) {
    print("fizz")
  } else if (as.integer(s) %% 5 == 0) {
    print("buzz")
  }
}


 

3.  **Mario Challenge:** In the classic Super Mario games, Mario ends each level by ascending a flight of stairs and leaping off the top to arrive at the castle at the end. (See [here](https://youtu.be/-avspZlbOWU?t=55) for details). We can imagine that each of the bricks of the stairs is a character X. Create a function that prints out a set of stairs. For example:

    If the function is called marioStairs() and we pass in the value 4, we would expect to see stairs with a length of 4 and a height of 4:

    X

    XX

    XXX

    XXXX

    ```{r}
    # You may feel more comfortable figuring this out in Python first, then translating into R later.
    
    
marioStars <- function(x) {
for (num in 1:x) {
  cat(rep("x", num), "\n")
  }
}

marioStars(4)
    
